version: '3.8'

services:
  sveltekit:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - HTTPS=true
    depends_on:
      - pocketbase
    command: sh -c "yarn install && yarn run dev"

  pocketbase:
    # image: elestio/pocketbase:latest
    build:
      dockerfile: Dockerfile.pb
    ports:
      - '8090:8090'
    volumes:
      - ./pb_data:/pb_data
    command: ['/pb/pocketbase', 'serve', '0.0.0.0:8090']
